import {
    LuSearch,
    LuArrowUpRight,
    LuArrowLeft,
    LuArrowRight,
    LuChevronDown,
    LuChevronUp,
    LuChevronLeft,
    LuChevronRight,
    LuMenu,
    LuGlobe,
    LuMessageSquare,
    LuShoppingCart,
    LuBox,
    LuCheck,
    LuX,
    LuPlus,
    LuMinus,
    LuEye,
    LuEyeOff,
    LuBell,
    LuZap,
    LuGamepad2,
    LuStar,
    LuUsers,
    LuClipboardList,
    LuLayoutDashboard,
    LuCircleHelp,
    LuPencil,
    LuTrash2,
    LuShieldCheck,
    LuStore,
    LuWallet,
    LuTrendingUp,
    LuMail,
    LuClock,
    LuTag,
    LuCrown,
    LuLogOut,
    LuInfo,
    LuCircleCheck,
    LuCircleAlert,
    LuTriangleAlert,
    LuPlay,
    LuPause,
    LuHeadphones,
    LuSlidersHorizontal,
    LuSparkles,
    LuLayers,
} from 'react-icons/lu';
import { SiDiscord } from 'react-icons/si';

const ICONS = {
    search: LuSearch,
    'arrow-up-right': LuArrowUpRight,
    'arrow-left': LuArrowLeft,
    'arrow-right': LuArrowRight,
    'chevron-down': LuChevronDown,
    'chevron-up': LuChevronUp,
    'chevron-left': LuChevronLeft,
    'chevron-right': LuChevronRight,
    menu: LuMenu,
    globe: LuGlobe,
    discord: SiDiscord,
    message: LuMessageSquare,
    cart: LuShoppingCart,
    box: LuBox,
    check: LuCheck,
    x: LuX,
    plus: LuPlus,
    minus: LuMinus,
    eye: LuEye,
    'eye-off': LuEyeOff,
    bell: LuBell,
    bolt: LuZap,
    gamepad: LuGamepad2,
    star: LuStar,
    users: LuUsers,
    clipboard: LuClipboardList,
    dashboard: LuLayoutDashboard,
    'circle-help': LuCircleHelp,
    edit: LuPencil,
    trash: LuTrash2,
    shield: LuShieldCheck,
    store: LuStore,
    wallet: LuWallet,
    'trending-up': LuTrendingUp,
    mail: LuMail,
    clock: LuClock,
    tag: LuTag,
    crown: LuCrown,
    logout: LuLogOut,
    info: LuInfo,
    'check-circle': LuCircleCheck,
    'alert-circle': LuCircleAlert,
    'alert-triangle': LuTriangleAlert,
    play: LuPlay,
    pause: LuPause,
    headset: LuHeadphones,
    sliders: LuSlidersHorizontal,
    sparkles: LuSparkles,
    layers: LuLayers,
};

export default function Icon({ name, className = 'w-5 h-5', strokeWidth = 2, ...props }) {
    const IconComponent = ICONS[name] ?? ICONS.box;
    return (
        <IconComponent
            className={className}
            strokeWidth={strokeWidth}
            aria-hidden="true"
            {...props}
        />
    );
}